sudo: false

cache:
  directories:
    - test/elm-stuff/build-artifacts

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.18.0 TARGET_NODE_VERSION=node
    - ELM_VERSION=0.18.0 TARGET_NODE_VERSION=4.0

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - cd tests
  - npm install -g elm@$ELM_VERSION elm-test
  - elm package install --yes
  - cd ..

script:
  - npm test
